services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: keycloak_db
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql:/docker-entrypoint-initdb.d
    env_file:
      - ./docker/.env

  keycloak:
    image: mykeycloak
    container_name: keycloak
    build:
      context: ./docker/keycloak
      dockerfile: Dockerfile
    env_file:
      - ./docker/.env  
    volumes:
      - ./docker/keys:/home/app/keys
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=changeit
      - JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      - JGROUPS_DISCOVERY_PROPERTIES: initial_hosts=keycloak1[7600],keycloak2[7600];port_range=10
    ports:
      - "${KEYCLOAK_PORT}:8443"
    command: >
      start --optimized  --https-key-store-file=/home/app/keys/keystore.jks --https-key-store-password=changeit

  myapp:
    image: dds_permission_manager
    container_name: dds_permission_manager
    build:
      context: ./app/build/docker/main/
      dockerfile: Dockerfile
    env_file:
      - ./docker/.env    
    environment:
      - DPM_JDBC_PASSWORD=${PGPASSWORD}
      - JWT_PRIVATE_KEY=/home/app/keys/pkcs8.key
      - JWT_PUBLIC_KEY=/home/app/keys/publickey.crt
    ports:
      - "${DDS_PORT}:8443"
    volumes:
      - ./docker/keys:/home/app/keys
    entrypoint: >
      /bin/sh -c "\
        sleep 40 && \
        keytool -importcert -alias keytool-ca -file /home/app/keys/certificate.crt -cacerts -storepass changeit -noprompt && \
        keytool -list -v -alias keytool-ca -cacerts -storepass changeit && \
        java -Djavax.net.debug=trustmanager -jar application.jar \
      "
